- name: Performs package manipulations - {{ other.host.address }}
  hosts: "{{ other.host.address }}"
  gather_facts: no
  vars_files:
    - vars/libguestfs.yml
  any_errors_fatal: true
  tasks:

     - name: Append line to file in guest disk image
       include_role:
         name: append_line
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['append'] is defined
         - other['append']['line'] is defined

     - name: Change file/directory permission in guest disk image
       include_role:
         name: guest_permission
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['guest'] is defined
         - other['guest']['permission'] is defined

     - name: Create symbolic link to file in guest disk image
       include_role:
         name: guest_link
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['guest'] is defined
         - other['guest']['link'] is defined

     - name: Create directory in guest disk image
       include_role:
         name: guest_directory
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['guest'] is defined
         - other['guest']['directory'] is defined

     - name: Move file/directory in guest disk image
       include_role:
         name: move_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['move'] is defined
         - other['move']['inside'] is defined
