- name: Performs package manipulations - {{ other.host.address }}
  hosts: "{{ other.host.address }}"
  gather_facts: no
  vars_files:
    - vars/libguestfs.yml
  any_errors_fatal: true
  tasks:

     - name: Perform copy from executor host to guest disk image
       include_role:
         name: copy_to
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['copy'] is defined
         - other['copy']['to'] is defined

     - name: Perform copy inside guest disk image
       include_role:
         name: copy_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['copy'] is defined
         - other['copy']['inside'] is defined

     - name: Perform delete inside guest disk image
       include_role:
         name: delete_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['delete'] is defined

     - name: Append line to file in guest disk image
       include_role:
         name: append_line
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['append'] is defined
         - other['append']['line'] is defined

     - name: Change file/directory permission in guest disk image
       include_role:
         name: guest_permission
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['guest'] is defined
         - other['guest']['permission'] is defined

     - name: Create symbolic link to file in guest disk image
       include_role:
         name: guest_link
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['guest'] is defined
         - other['guest']['link'] is defined

     - name: Create directory in guest disk image
       include_role:
         name: guest_directory
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['guest'] is defined
         - other['guest']['directory'] is defined

     - name: Move file/directory in guest disk image
       include_role:
         name: move_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['move'] is defined
         - other['move']['inside'] is defined

     - name: Scrub file in guest disk image
       include_role:
         name: scrub_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when: 
         - other['scrub'] is defined
         - other['scrub']['build'] is not defined

     - name: Truncate file in guest disk image
       include_role:
         name: truncate_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['truncate'] is defined
         - other['truncate']['recursive'] is not defined

     - name: Truncate path in guest disk image
       include_role:
         name: truncate_recursive_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['truncate'] is defined
         - other['truncate']['recursive'] is defined

     - name: Create a file in guest disk image
       include_role:
         name: create_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when: other['create'] is defined

     - name: Perform upload from executor host to guest disk image
       include_role:
         name: upload_to
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['upload'] is defined
         - other['upload']['to'] is defined

     - name: Write content to file in guest disk image
       include_role:
         name: write_content
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['write'] is defined
         - other['write']['content'] is defined
