- name: Performs guest manipulations - {{ other.host.address }}
  hosts: "{{ other.host.address }}"
  gather_facts: no
  vars_files:
    - vars/libguestfs.yml
  any_errors_fatal: true
  tasks:

     - name: Perform commands from file
       include_role:
         name: commands_file
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when: 
         - other['commands'] is defined
         - other['commands']['file'] is defined

     - name: Perform copy from executor host to guest disk image
       include_role:
         name: copy_to
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['copy'] is defined
         - other['copy']['to'] is defined

     - name: Perform copy inside guest disk image
       include_role:
         name: copy_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['copy'] is defined
         - other['copy']['inside'] is defined

     - name: Perform delete inside guest disk image
       include_role:
         name: delete_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['delete'] is defined

     - name: Script file to be executed on guest disk image during firstboot
       include_role:
         name: firstboot_file
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['firstboot'] is defined
         - other['firstboot']['file'] is defined

     - name: Command to be executed on guest disk image during firstboot
       include_role:
         name: firstboot_command
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['firstboot'] is defined
         - other['firstboot']['command'] is defined

     - name: Sets a hostname in guest disk image
       include_role:
         name: guest_hostname
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['guest'] is defined
         - other['guest']['hostname'] is defined

     - name: Sets a user's password in guest disk image
       include_role:
         name: user_password
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['user'] is defined
         - other['user']['password'] is defined

     - name: Sets a root's password in guest disk image
       include_role:
         name: root_password
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['root'] is defined
         - other['root']['password'] is defined

     - name: Run a program/script in guest disk image
       include_role:
         name: run_script
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['run'] is defined
         - other['run']['script'] is defined
