- name: Performs guest manipulations - {{ other.host.address }}
  hosts: "{{ other.host.address }}"
  gather_facts: no
  vars_files:
    - vars/libguestfs.yml
  any_errors_fatal: true
  tasks:

     - name: Perform commands from file
       include_role:
         name: commands_file
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when: 
         - other['commands'] is defined
         - other['commands']['file'] is defined

     - name: Perform copy from executor host to guest disk image
       include_role:
         name: copy_to
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['copy'] is defined
         - other['copy']['to'] is defined

     - name: Perform copy inside guest disk image
       include_role:
         name: copy_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['copy'] is defined
         - other['copy']['inside'] is defined

     - name: Perform delete inside guest disk image
       include_role:
         name: delete_inside
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['delete'] is defined

     - name: Script file to be executed on guest disk image during firstboot
       include_role:
         name: firstboot_file
       with_items: "{{ hostvars['localhost']['images'] }}"
       loop_control:
         loop_var: image
       when:
         - other['firstboot'] is defined
         - other['firstboot']['file'] is defined
