- name: Set plugin invocation host
  hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true
  tasks:

     - name: image-remote, image-url and image-local are mutually exclusive
       block:
         - fail:
             msg: "image-remote, image-url and image-local are mutually exclusive"
           when:
             - other['image'] is defined
             - (other['image']['remote'] is defined and other['image']['url'] is defined) or
               (other['image']['remote'] is defined and other['image']['local'] is defined) or
               (other['image']['url'] is defined and other['image']['local'] is defined)

         - set_fact:
             images: "{{ other['image']['remote'] }}"
           when: other['image']['remote'] is defined

         - set_fact:
             images: "{{ other['image']['url'] }}"
             images_action: download
           when: other['image']['url'] is defined

         - set_fact:
             images: "{{ other['image']['local'] }}"
             images_action: transfer
           when: other['image']['local'] is defined

     - debug:
         var: images

     - name: Set invocation host
       set_fact:
          other:
            host:
              address: "{{ other['host']['address'] }}"

     - name: Set virt-customize variables
       block:
         - name: Create variable
           set_fact:
             _vc_args: null

         - name: Set memory parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -m {{ other['memory'] }}"
           when: other['memory'] is defined

         - name: Set memory parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -smp {{ other['cpu'] }}"
           when: other['cpu'] is defined

         - name: Set verbosity parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -v"
           when: other['verbosity']

         - name: Set debug/trace parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -x"
           when: other['trace']

         - name: Scrub build log of virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} --no-logfile"
           when:
             - other['scrub'] is defined
             - other['scrub']['build'] is defined
             - other['scrub']['build']['log']

         - name: Parse images path
           set_fact:
             images: "{{ images.split(',') }}"
