- name: Perform prerequsites on - {{ other.host.address }}
  hosts: "{{ other.host.address }}"
  gather_facts: no
  any_errors_fatal: true
  tasks:

     - name: Install libguestfs
       yum:
         name: libguestfs-tools-c
         state: latest
       when:
         - other['skip'] is defined
         - other['skip']['install'] is defined
         - other['skip']['install']['tools'] == false

     - name: Verify existence of images on executor host
       stat:
         path: "{{ item }}"
       with_items: "{{ hostvars['localhost']['images'] }}"
       failed_when: file_existence['stat']['exists'] == false
       register: file_existence
