- name: Set plugin invocation host
  hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true
  tasks:

     - name: Set invocation host
       set_fact:
          other:
            host:
              address: "{{ other['host']['address'] }}"

     - name: Set virt-customize variables
       block:
         - name: Create variable
           set_fact:
             _vc_args: ""

         - name: Set memory parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -m {{ other['memory'] }}"
           when: other.memory is defined

         - name: Set memory parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -smp {{ other['cpu'] }}"
           when: other.cpu is defined

         - name: Set verbosity parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -v"
           when: other.verbosity

         - name: Set debug/trace parameter in virt-customize
           set_fact:
             _vc_args: "{{ _vc_args }} -x"
           when: other.trace

         - name: Parse images path
           set_fact:
             images: "{{ other['image'].split(',') }}"
