- name: Assign file to create in guest disk image to virt-customize arg
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --touch {{ other['create'] }}"

- name: Create a file in guest disk image
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"
