- name: Parse file details
  set_fact:
    guest_file: "{{ other['write']['content'].split(':')[0] }}"
    file_content: "{{ other['write']['content'].split(':')[1] }}"
  failed_when: other['write']['content'].split(':')[1] is not defined

- name: Assign file details to virt-customize arg
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --write {{ guest_file }}:{{ file_content }}"

- name: Write content to file in guest disk image
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"
