- name: Assign run to virt-customize arg
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --run {{ other['run']['script'] }}"

- name: Run script (located on disk-image) in guest disk image
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"
