- name: Parse file details
  set_fact:
    guest_file: "{{ other['write']['content'].split(':')[0] }}"
    file_content: "{{ other['write']['content'].split(':')[1] }}"
  failed_when: other['write']['content'].split(':')[1] is not defined

- name: Assign file details to virt-customize arg
  set_fact:
    _vc_args: "{{ hostvars['localhost']['_vc_args'] } --write {{ guest_file }}:{{ file_content }}"

- name: Print virt-customize command
  debug:
    msg: "virt-customize {{ _vc_args }} -a {{ image }}"

- name: Execute command
  shell: >
    virt-customize {{ _vc_args }}
    -a {{ image }}
  environment:
    LIBGUESTFS_BACKEND: "{{ LIBGUESTFS_BACKEND }}"
    LIBGUESTFS_BACKEND_SETTINGS: "{{ LIBGUESTFS_BACKEND_SETTINGS }}"
