- name: Parse subscription manager user details
  set_fact:
    sm_user: "{{ other['sm']['credentials'].split(':')[0] }}"
    sm_password: "{{ other['sm']['credentials'].split(':')[1] }}"
  failed_when: other['sm']['credentials'].split(':')[1] is not defined

- name: Assign subscription manager registration arguments to virt-customize arg
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --sm-register --sm-credentials {{ sm_user }}:password:{{ sm_password }}"

- name: Register to subscription manager
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"
