- name: Assign root details to virt-customize arg
  set_fact:
    _vc_args: "{{ hostvars['localhost']['_vc_args'] }} --root-password password:{{ other['root']['password'] }}"

- name: Print virt-customize command
  debug:
    msg: "virt-customize {{ _vc_args }} -a {{ image }}"

- name: Execute command
  shell: >
    virt-customize {{ _vc_args }}
    -a {{ image }}
  environment:
    LIBGUESTFS_BACKEND: "{{ LIBGUESTFS_BACKEND }}"
    LIBGUESTFS_BACKEND_SETTINGS: "{{ LIBGUESTFS_BACKEND_SETTINGS }}"
