- name: Genrate temp filename
  set_fact:
    remote_file: "/tmp/{{ other['commands']['file'] | to_uuid }}"

- name: Copy file from infrared client to executor host
  copy:
    src: "{{ other['commands']['file'] }}"
    dest: "{{ remote_file }}"

- name: Assign commands-file to virt-customize arg
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --commands-from-file {{ remote_file }}"

- name: Run virt-customize commands from file on guest disk image
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"

- name: Delete temp file
  file:
    path: "{{ remote_file }}"
    state: absent
