- name: Genrate temp filename
  set_fact:
    remote_file: "/tmp/{{ other['commands']['file'] | to_uuid }}"

- name: Copy file from infrared client to executor host
  copy:
    src: "{{ other['commands']['file'] }}"
    dest: "{{ remote_file }}"

- name: Assign commands-file to virt-customize arg
  set_fact:
    _vc_args: "{{ hostvars['localhost']['_vc_args'] }} --commands-from-file {{ remote_file }}"

- name: Print virt-customize command
  debug:
    msg: "virt-customize {{ _vc_args }} -a {{ image }}"

- name: Execute command
  shell: >
    virt-customize {{ _vc_args }}
    -a {{ image }}
  environment:
    LIBGUESTFS_BACKEND: "{{ LIBGUESTFS_BACKEND }}"
    LIBGUESTFS_BACKEND_SETTINGS: "{{ LIBGUESTFS_BACKEND_SETTINGS }}"

- name: Delete temp file
  file:
    path: "{{ remote_file }}"
    state: absent
