- name: Assign timezone to virt-customize arg
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --timezone {{ other['guest']['timezone'] }}"

- name: Set a timezone in guest disk image
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"
