- name: Assign unregister from subscription manager arg to virt-customize
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --sm-unregister"

- name: Create a file in guest disk image
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"
