- name: Parse user details
  set_fact:
    guest_user: "{{ other['user']['password'].split(':')[0] }}"
    guest_password: "{{ other['user']['password'].split(':')[1] }}"
  failed_when: other['user']['password'].split(':')[1] is not defined

- name: Assign user details to virt-customize arg
  set_fact:
    vc_args: "{{ hostvars['localhost']['_vc_args'] }} --password {{ guest_user }}:password:{{ guest_password }}"

- name: Set password crypto method
  set_fact:
    vc_args: "{{ _vc_args }} --password-crypto {{ other['password']['crypto'] }}"
  when:
    - other['password'] is defined
    - other['password']['crypto'] is defined

- name: Set a user's password in guest disk image
  include_role:
    name: execute_command
  vars:
    _vc_args: "{{ vc_args }}"
    _image: "{{ image }}"
