- name: Parse file locations
  set_fact:
    client_src_file: "{{ other['copy']['to'].split(':')[0] }}"
    guest_dest_file: "{{ other['copy']['to'].split(':')[1] }}"
  failed_when: other['copy']['to'].split(':')[1] is not defined

- name: Verify file existence on infrared client
  stat:
    path: "{{ client_src_file }}"
  failed_when: file_existence['stat']['exists'] == false
  register: file_existence
  delegate_to: localhost

- name: Genrate temp filename
  set_fact:
    remote_file: "/tmp/{{ client_src_file | to_uuid }}"

- name: Copy file from infrared client to executor host
  copy:
    src: "{{ client_src_file }}"
    dest: "{{ remote_file }}"

- name: Assign host src and guest dest files to virt-customize arg
  set_fact:
    _vc_args: "{{ hostvars['localhost']['_vc_args'] }} --copy-in {{ remote_file }}:{{ guest_dest_file }}"

- name: Print virt-customize command
  debug:
    msg: "virt-customize {{ _vc_args }} -a {{ image }}"

- name: Execute command
  shell: >
    virt-customize {{ _vc_args }}
    -a {{ image }}
  environment:
    LIBGUESTFS_BACKEND: "{{ LIBGUESTFS_BACKEND }}"
    LIBGUESTFS_BACKEND_SETTINGS: "{{ LIBGUESTFS_BACKEND_SETTINGS }}"
